### ISSUE TITLE
Failure with dev tibble

### ISSUE THREAD

**Issue by krlmlr** [erictleung/pixarfilms#19]
A recent change in tibble 3.1.3 breaks output tests in this package, I'd like to release to CRAN soon. An easy workaround is to change this to snapshot tests which are ignored on CRAN, however this requires  all tests to be compatible with testthat edition 3.

**Comment by erictleung** [comment]
Thanks @krlmlr for letting me know! I'll try to make some time to make this update. I've noticed that Hadley's {babynames} package made some similar changes and I hope to emulate some of that code https://github.com/hadley/babynames.

**Comment by erictleung** [comment]
Closed by https://github.com/erictleung/pixarfilms/commit/1eae5be2642e89443cf1d874874023c9bc034a1c
